name: check-go-mod

on:
  workflow_call:
    inputs:
      runs-on:
        description: An expression indicating which kind of runners to use.
        required: true
        type: string
      repository-name:
        required: true
        type: string
    secrets:
      elevated-github-token:
        required: true
jobs:
  check-go-mod:
    runs-on: ${{ fromJSON(inputs.runs-on) }}

    steps:
    - uses: actions/checkout@b80ff79f1755d06ba70441c368a6fe801f5f3a62 # pin@v3.3.0
    # NOTE: This step is specifically needed for ENT. It allows us to access the required private HashiCorp repos.
    - name: Setup Git
      if: ${{ endsWith(inputs.repository-name, '-enterprise') }}
      run: git config --global url."https://${{ secrets.elevated-github-token }}:@github.com".insteadOf "https://github.com"
    - uses: actions/setup-go@883490dfd06f396ebe0b738bc313a53cf9d851e5 # pin@v3.5.0
      with:
        go-version-file: 'go.mod'
    - run: go mod tidy
    - run: |
        if [[ -n $(git status -s) ]]; then
          echo "Git directory has changes"
          git status -s
          exit 1
        fi
    - name: Notify Slack
      if: ${{ failure() }}
      run: .github/scripts/notify_slack.sh
